### ISSUE TITLE
Trying to use system mv command:

### ISSUE THREAD

**Issue by Lunreth** [dordnung/Cronjobs-SM#1]
Hello,

I wanted to know if this syntax is correct, since i tried to get Cronjobs plugin to work but failed lots of times.

// Use MG server.cfg at 5 pm on every sunday by changing name of file
0 17 * * 7 system mv "/nmrih/cfg/server.cfg" "/nmrih/cfg/server-backup.cfg"
0 17 * * 7 system mv "/nmrih/cfg/server-mg.cfg" "/nmrih/cfg/server.cfg"

Just to clarify, my dedicated server SRCDS is Windows 7 and their folders are located like this:
C:\Program Files (x86)\Steam\steamcmd\nmrih_ds\nmrih\cfg\server.cfg

Am i doing something wrong? Should i put the whole path? Should i use "/home/user/server/nmrih/cfg/server.cfg"? Replacing user with username and server with... dont know?

I previously tried (with no success):
0 17 * * 7 system mv nmrih/cfg/server.cfg nmrih/cfg/server-backup.cfg
0 17 * * 7 system mv nmrih/cfg/server-mg.cfg nmrih/cfg/server.cfg

**Comment by dordnung** [comment]
Yes you have to use the absolute path, but _/home/user/server/nmrih/cfg/server.cfg_ is a unix path, not Windows. So you have to use _"C:\Program Files (x86)\Steam\steamcmd\nmrih_ds\nmrih\cfg\"_
